openapi: 3.0.0
info:
  description: This API receives events from software application
  version: "1.0.0"
  title: Laundry Service Request
  contact:
    email: h2@my.bcit.ca
tags:
  - name: laundry providers
    description: Secured laundry-provider-only sessions
  - name: users
    description: Secured user-only sessions
paths:
  /laundryRegister:
    post:
      tags:
        - laundry providers
      summary: reports the laundromat location
      operationId: app.report_laundry_provider_location
      description: Saves laundry provider location to the system
      responses:
        '201':
          description: Register the laundry service provider
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportService'
        description: Laundry service provider information to add
  /requestService:
    post:
      tags:
        - users
      summary: reports the service requested
      operationId: app.report_service_requested
      description: Saves the service requested to the system
      responses:
        '201':
          description: Service created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestService'
        description: Service to add
components:
  schemas:
    ReportService:
      type: object
      required:
        - businessID
        - serviceOffered
        - openingHours
        - closingHours
        - phoneNumber
        - streetAddress
      properties:
        businessID:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851 
        serviceOffered:
          type: string
          example: Dry clean
        openingHours:
          type: string
          format: date-time
          example: 2020-08-29T09\:12\:33.001Z
        closingHours:
          type: string
          format: date-time
          example: 2020-08-29T09\:12\:33.001Z
        phoneNumber:
          type: string
          pattern: '^\d{3}-\d{3}-\d{4}$'
          example: 123-456-7890
        streetAddress:
          $ref: '#/components/schemas/StreetAddress'
    RequestService:
      type: object
      required:
        - serviceType
        - laundryType
        - numberOfItems
        - phoneNumber
        - emailAddress
        - streetAddress
      properties:
        serviceType:
          type: string
          example: Dry Clean
        laundryType:
          type: string
          example: Bridal dress
        numberOfItems:
          type: number
          example: 3
        phoneNumber:
          type: string
          pattern: '^\d{3}-\d{3}-\d{4}$'
          example: 123-456-7890
        emailAddress:
          type: string
          format: email
          example: email@example.com
        streetAddress:
          $ref: '#/components/schemas/StreetAddress'
    StreetAddress:
      type: object
      required:
        - streetNumber
        - city
        - province
        - country
        - postalCode
      properties:
        streetNumber:
          type: string
          example: 12345 678 St
        city:
          type: string
          example: Vancouver
        province:
          type: string
          example: British Columbia
        country:
          type: string
          example: Canada
        postalCode:
          type: string
          example: A1B2C3
