openapi: 3.0.0
version: 1
datastore:
  user: "user"
  password: "password"
  hostname: "localhost"
  port: 3306
  db: events
  filename: /data/data.json
scheduler:
  period_sec: 5
eventstore:
  url: http://localhost:8090
