openapi: 3.0.0
version: 1
datastore:
  user: "user" # RemoteDB username
  password: "password" # RemoteDB password
  hostname: mysbalab.eastus2.cloudapp.azure.com
  port: 3306
  db: events

events:
  hostname: mysbalab.eastus2.cloudapp.azure.com
  port: 9092
  topic: events
